### ISSUE TITLE
These two _id's register invalid

### ISSUE THREAD

**Issue by stocksp** [SteveRidout/mongo-object-time#3]
though Mongo obviously likes (and generated them)

`"nRjTsizg2KXbcAsJM"`
and
`"Rt2SLZW8bvrGnACmN"`

**Comment by SteveRidout** [comment]
Hmm, I'm used to the hexadecimal encoding for ObjectId strings, and those look like they are using a different kind of encoding. How exactly did you generate those strings?

**Comment by stocksp** [comment]
Meteor .... and that's the issue .....   I'll close this
Here is from the docs:

"ObjectID values created by Meteor will not have meaningful answers to their getTimestamp method, since Meteor currently constructs them fully randomly."

I wish this was the only non standard thing Meteor did ....   sorry for the noise.
