### ISSUE TITLE
How to convert from ISO Timestamp back to Mongo Object Id

### ISSUE THREAD

**Issue by ngohungphuc** [SteveRidout/mongo-object-time#5]
I have object id like this 5a01de5f990092a25640e1e6

I'm using the function you provide
```
var objectIdFromDate = function (date) {
	return Math.floor(date.getTime() / 1000).toString(16) + "0000000000000000";
};
```

but the data return back for me only is just `5a01de5f`
the iso timestamp i'm have is `2017-11-07T16:25:03Z`

**Comment by SteveRidout** [comment]
You can generate many different MongoIDs from the same timestamp so you can't "recover" a specific object ID from a timestamp. Think about it - what if you wanted to create many objects at the exact same time? They all need a unique ID.

**Comment by ngohungphuc** [comment]
So I dont any other to convert back to mongo object ID ?
